kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pgo-osb
subjects:
  - kind: ServiceAccount
    name: pgo-osb
    namespace: $CO_NAMESPACE
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pgo-osb

