kind: Service
apiVersion: v1
metadata:
  name: pgo-osb
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: 'pgo-osb-ssl'
  labels:
    app: pgo-osb
spec:
  selector:
    app: pgo-osb
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8443
