apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: testinstance
  namespace: $OSB_NAMESPACE
spec:
  clusterServiceClassExternalName: pgo-osb-service
  clusterServicePlanExternalName: default
  parameters:
    PGO_USERNAME: username
    PGO_PASSWORD: password
    PGO_CLUSTERNAME: testinstance
    PGO_NAMESPACE: $PGO_NAMESPACE
