kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pgo-osb-client
subjects:
  - kind: ServiceAccount
    name: pgo-osb-client
    namespace: $OSB_NAMESPACE
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: access-pgo-osb

