kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: pgo-osb
  labels:
    app: pgo-osb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgo-osb
  template:
    metadata:
      labels:
        app: pgo-osb
    spec:
      serviceAccount: pgo-osb
      containers:
      - env:
        - name: CRUNCHY_DEBUG
          value: "true"
        name: service-pgo-osb
        image: $CO_IMAGE_PREFIX/pgo-osb:$CO_IMAGE_TAG
        imagePullPolicy: IfNotPresent
        command:
        - /usr/local/bin/pgo-osb
        args:
        - --port
        - "8443"
        - -v
        - "4"
        - --CO_USERNAME
        - "username"
        - --CO_PASSWORD
        - "password"
        - --PGO_OSB_GUID
        - "4be12541-2945-4101-8a33-79ac0ad58750"
        - --CO_APISERVER_URL
        - "https://postgres-operator:8443"
        - --CO_APISERVER_VERSION
        - "3.1"
        - --insecure
        - "true"
        - --logtostderr
        - --tls-cert-file
        - ""
        - --tls-private-key-file
        - ""
        - --authenticate-k8s-token
        ports:
        - containerPort: 8443
        readinessProbe:
          httpGet:
            path: /healthz
            scheme: HTTP
            port: 8443
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        volumeMounts:
        - mountPath: /var/run/pgo-osb
          name: pgo-osb-ssl
          readOnly: true
        - mountPath: /opt/apiserver-keys
          name: apiserver-keys
          readOnly: true
      volumes:
      - name: apiserver-keys
        secret:
          defaultMode: 420
          secretName: pgo-osb-apiserver-secret
          items:
          - key: ca
            path: ca.crt
          - key: clientkey
            path: client.key
          - key: clientcert
            path: client.crt
      - name: pgo-osb-ssl
        secret:
          defaultMode: 420
          secretName: pgo-osb-tls-secret
          items:
          - key: tls.crt
            path: server.crt
          - key: tls.key
            path: server.key
