FROM centos:7

LABEL Vendor="Crunchy Data Solutions" \
        Version="1.2.3" \
        Release="1.2.3" \
        summary="Crunchy Data pgo-osb open service broker " \
        description="Crunchy Data PostgreSQL Operator - pgo-osb "


ADD ./pgo-osb /usr/local/bin/

CMD /usr/local/bin/pgo-osb --help
